scottie1984/swagger-ui-express

- README.md
- index.js
- package.json
- test/test.spec.js
- test/testapp/app.js
- test/testapp/run.js
I found myself in a position where I wanted to use this library, but wasn't able to update the version of node running the app. The version the server is running is v0.10.32 (pretty old) and doesn't support fat-arrow functions, const, etc. Here is the code if you  are interested in including it to reach others in the same position.
Additionally, I modified the tests so that they are passing now and confirm the UI elements are present as expected.
> Make compatible w/ older versions of node

- README.md
- index.js
- indexTemplate.html
Possible fix for #6 
With this PR you can add arbitrary CSS to the swagger HTML page, to style it differently.
E.g. to remove the swagger header you could do this:
```javascript
var customCss = '#header { display: none }';
app.use('/api-docs', SwaggerUi.serve, SwaggerUi.setup(swaggerDoc, false, {}, customCss));
> Add custom css

- index.js
Greetings,
This PR allows specifying functions in the third setup param for swagger options. I recently needed to implement a header workaround that could only be accomplished using the `onComplete` cb function.
I've added a `stringify` function which provides a `replacer` that handles functions - other value type handling remains unchanged.
Thank you for your work in putting together this package.
> custom stringify that provides a reviver to allow stringifying option function - i.e. onComplete

- indexTemplate.html
This is the PR that containing my code to support setting OAuth parameters that are available in swagger-ui (see https://github.com/swagger-api/swagger-ui), which is based on the idea mentioned in #5
> Support specify OAuth parameters via options.oauth

- README.md
- index.js
- indexTemplate.html
- test/test.spec.js
- test/testapp/app.js
Following up on #20, this PR adds the `swaggerUrl` option to the `setup` function.
This allows things like:
1. Allowing relative `$ref` paths if your swagger is split into multiple files
1. Showing the link to the swagger definition in the UI without having to specify the path in the URL query string
1. Checking your swagger against the online validator (if it's accessible to the open internet)
I wanted to get this up here to get feedback, but I still have to:
1. Get the tests running, I've tested the changes manually but I'm having some trouble getting the automated tests to pass, so I'll take another shot at that tomorrow
1. Update the README
> Add `swaggerUrl` to setup function, as alternative to `swaggerDoc`

- indexTemplate.html
swagger-ui 3.17.3 included https://github.com/swagger-api/swagger-ui/pull/4598, which stopped using Google Web Fonts, so it's no longer necessary to load the Google Web Fonts CSS.
For the record there's still [one accidental reference left](https://github.com/swagger-api/swagger-ui/pull/4840), but that will just fall back to `sans-serif` if nothing is providing the font via a `@font-face` declaration. So this PR isn't really blocked on the other one.
> Don't load the Google Web Fonts CSS anymore

- .travis.yml
- index.js
- swagger-ui-init.js
Support for parameter `urls` of the `sqagger-ui` library was added.
Usage example
```
app.use(
"/api-docs",
swaggerUi.serve,
swaggerUi.setup(undefined, {
swaggerUrls: [
{ url: "pathToFirstDocument", name: "FirstDocument" },
{ url: "pathToSecondDocument", name: "SecondDocument" }
]
})
);
```
> Support for the url parameter of the swagger-ui library

- package.json
Small issue when using node v12 with "--experimental-modules" and "--es-module-specifier-resolution=node" flags because package.json refers to non-existing file.
See https://github.com/kroonprins/swagger-ui-express-test for example of the error.
> Correct main in package.json

- README.md
- index.js
During development we work with many micro-services. in swagger 2 you can only have a single host which poses a problem during development and the developers was to use the swagger to test their api.
This pr injects the swagger doc into the req object and thus allowing the dev to inject an additional middleware into the mix.. in the readme (and the one I use from the fork), I can modify the swagger host based on the express host within the request object. This dynamically sets the host based on the env the ap is running, local -> dev -> int etc etc.
> Optionally pass the swagger doc into the req object

- README.md
- index.js
I couldn't get the dynamic hostname feature introduced in #142 to work. Looking into the history of the repository I found that https://github.com/scottie1984/swagger-ui-express/commit/d10791ba2f248ecff1fffdc2d4c3a6f2cdc4896d is the reason why. This fix is using the old `swaggerDoc`, instead of the one provided by the request.
* Use the correct `swaggerDoc` when one is provided in the request
* Fix the example in the readme as it's referring to a non-existing variable.
> Fix request swagger document not being used

- index.js
Refactor function assignment to function expression in middleware in order to track function calls in monitor services like [NewRelic](https://newrelic.com/).
Otherwise `Middleware <anonymous>` is shown in the dashboard.
> fix: name middleware

- index.js
This fixes a typo in `customSiteTitle`.
> fix: Typo in customSiteTitle

- package.json
The main one of concern that prompted this was this XSS vulnerability (https://github.com/swagger-api/swagger-ui/releases/tag/v3.24.1) but there are a handful of other security fixes that the updated version has.
> Update swagger-ui-dist dependency to fix security vulnerabilities

- index.js
It's posible when used webserver to send requests with query params or just "?" sign.
Then expression do not match and we cannot get generated swagger-ui-init.js.
> Trim req.url from query params

- index.js
swagger-ui-init.js and package.json are compared with endsWith now.
Reason: While using Nest.Js + azure function http adapter, the url contains the hostname and the check with === does not work
> Url checking improved

- index.js
For integrating a Swagger plugin I need to be able to include external Javascript.
This works for exactly one because the opts parameter accepts exactly one URL for external Javascript via the customJs property.
If I want to use a second Swagger plugin or want to include other Javascript code there is no direct way without "hacking".
This PR removes the constraint to only being able to import one external script, one external css and one inline script by accepting strings and arrays for the customJs, customJsStr and customCssUrl parameter.
> Accept multiple Javascript and CSS imports

- README.md
[yamljs](https://www.npmjs.com/package/yamljs) hasn't been maintained for 5 years, so it's better to use [yaml](https://www.npmjs.com/package/yaml) that is more up-to-date and performs the same function. So, I updated that section.
> replace yamljs to yaml

- index.js
Add the possibility to specify a custom Robots meta through the options parameter in `setup` and `generateHTML`. This allows hiding the swagger page from search engines like google by specifying `customRobots: "noindex,follow"` in the options object.
This is currently not possible though `customJs` for example as `customJs` alters the page after load which will then cause crawlers to not pick it up.
> Custom robots meta tag

- index.js
- package.json
- test/test.spec.js
- test/testapp/app.js
- test/testapp/swagger.json
This PR addresses issue #311. 
The implementation needed a setInterval function call because of the unpredictable time that takes for the preauthorizeApiKey function to load schema definition.
Added proper unit testing as well
> Support for preauthorizeApiKey

- README.md
- index.js
- package.json
- test/test.spec.js
- test/testapp/app.js
`serveFiles` did not respect on-the-fly changes in a swagger doc,
but rendered the old content.
The fix now also enables this pattern, where `serveFiles` doesn't need
the swaggerDoc upfront (which is desired in dynamic cases):
```js
app.use('/api-docs-dynamic', function(req, res, next){
swaggerDocument.info.description = `Hello ${count}!`;
req.swaggerDoc = swaggerDocument;
next();
}, swaggerUi.serveFiles(), swaggerUi.setup());
//                     ^^^
```
Also fixes #318 which stumbled over the same issue, but draw the wrong
conclusion that the documentation would be wrong.
> Fix `serveFiles` to work w/ dynamic swaggerDoc

- package.json
Very small change of the version number seems to work without issue
All the tests pass and the test app works when opening http://localhost:3001/api-docs
Fixes: #349
> Update Swagger to 5.0.0

- index.js
This PR updates the import of `swagger-ui-dist` to only load the individual file used to get the path for the static assets, not the code of the static assets themself.
Before the entire dist lib was loaded which contains the entire code, a huge bundle.
I've noticed that in the project I'm working on (https://github.com/juice-shop/juice-shop/) the server takes about 150ms on startup loading the swagger-ui-dist packge.
Chaning his import drastically reduces the amount of code which needs to be loaded on the server side.
For us this means that swagger-ui becomes fast enough to be nearly unmeasurable, improving our total cpu load on start and total server start time by ~10% (`~1.2s -> ~1.1s`)
I've check briefly, from what I saw this should also work nicely with swagger-ui-dist v5.
Thank you …
> Performance Improvment: Only import required function / file of swagger-ui-dist

- package.json
chore(dev-dependency): update express
This pull request updates the `express` dependency in the `package.json` file to ensure compatibility with the latest features and security patches.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L32-R32): Updated `express` from version `^4.19.2` to `^4.21.0`.
> chore(dev-dependency): update express
